FROM ubuntu:22.04

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        curl \
        wget \
        unzip \
        apt-transport-https \
        libc6 \
        libgcc1 \
        libgssapi-krb5-2 \
        libicu70 \
        liblttng-ust1 \
        libssl3 \
        libstdc++6 \
        zlib1g \
        gnupg \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update \
    && apt-get install -y dotnet-sdk-8.0 \
    && apt-get install -y aspnetcore-runtime-8.0 \
    && apt-get install -y dotnet-runtime-8.0

RUN wget -q https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb \
    && dpkg -i packages-microsoft-prod.deb  \
    && apt-get update \
    && apt-get install azure-functions-core-tools-4 

WORKDIR /home/site/wwwroot
COPY . /home/site/wwwroot

EXPOSE 80

# Define the entry point for the Azure Functions host
ENTRYPOINT ["func", "host", "start", "--port", "80"]