# Generated by Django 5.0.4 on 2024-06-27 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('id_auth', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('author', models.ManyToManyField(db_table='author_images', to='publisher.author')),
            ],
        ),
        migrations.CreateModel(
            name='Cameras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, unique=True)),
                ('version', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('max_resolution', models.IntegerField()),
                ('sensor_size', models.IntegerField()),
                ('effective_pixels', models.IntegerField()),
                ('storage_types', models.CharField(max_length=100)),
                ('screen_size', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_comment='Date and time when the camera was created')),
                ('date_updated', models.DateTimeField(auto_now=True, db_comment='Date and time when the camera was updated')),
                ('author', models.ManyToManyField(db_table='cameras_authors', to='publisher.author')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(app_label)s_%(class)s_related', to='publisher.images')),
                ('video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='publisher.images')),
            ],
        ),
        migrations.CreateModel(
            name='Lens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelName', models.CharField(max_length=100, unique=True)),
                ('versionName', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('maxResolution', models.IntegerField()),
                ('sensorSize', models.IntegerField()),
                ('effectivePixels', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True, db_comment='Date and time when the len was created')),
                ('date_updated', models.DateTimeField(auto_now=True, db_comment='Date and time when the len was updated')),
                ('author', models.ManyToManyField(db_table='author_lens', to='publisher.author')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='publisher.images')),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('source', models.CharField(choices=[('YT', 'YouTube')], max_length=10)),
                ('credit', models.CharField(max_length=15)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_comment='Date and time when the video was created')),
                ('date_updated', models.DateTimeField(auto_now=True, db_comment='Date and time when the video was updated')),
                ('author', models.ManyToManyField(db_table='author_video', to='publisher.author')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True, db_comment='Date and time when the review was created')),
                ('date_updated', models.DateTimeField(auto_now=True, db_comment='Date and time when the review was updated')),
                ('author', models.ManyToManyField(db_table='author_reviews', to='publisher.author')),
                ('images', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='publisher.images')),
                ('lens', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='publisher.lens')),
                ('videos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='publisher.videos')),
            ],
        ),
        migrations.AddField(
            model_name='lens',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='publisher.videos'),
        ),
    ]
