# Generated by Django 5.0.4 on 2024-07-10 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='author',
        ),
        migrations.RemoveField(
            model_name='lens',
            name='image',
        ),
        migrations.RemoveField(
            model_name='review',
            name='images',
        ),
        migrations.RemoveField(
            model_name='lens',
            name='author',
        ),
        migrations.RemoveField(
            model_name='lens',
            name='video',
        ),
        migrations.RemoveField(
            model_name='review',
            name='lens',
        ),
        migrations.RemoveField(
            model_name='videos',
            name='author',
        ),
        migrations.RemoveField(
            model_name='review',
            name='videos',
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.ManyToManyField(db_table='publishers_reviews_authors', to='publisher.author'),
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, unique=True)),
                ('version', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('max_resolution', models.IntegerField()),
                ('sensor_size', models.IntegerField()),
                ('effective_pixels', models.IntegerField()),
                ('storage_types', models.CharField(max_length=100)),
                ('screen_size', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_comment='Date and time when the camera was created')),
                ('date_updated', models.DateTimeField(auto_now=True, db_comment='Date and time when the camera was updated')),
                ('author', models.ManyToManyField(db_table='publishers_cameras_authors', to='publisher.author')),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='camera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='publisher.camera'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('author', models.ManyToManyField(db_table='publishers_images_authors', to='publisher.author')),
            ],
        ),
        migrations.AddField(
            model_name='camera',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(app_label)s_%(class)s_related', to='publisher.image'),
        ),
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='publisher.image'),
        ),
        migrations.CreateModel(
            name='Len',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelName', models.CharField(max_length=100, unique=True)),
                ('versionName', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('maxResolution', models.IntegerField()),
                ('sensorSize', models.IntegerField()),
                ('effectivePixels', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True, db_comment='Date and time when the len was created')),
                ('date_updated', models.DateTimeField(auto_now=True, db_comment='Date and time when the len was updated')),
                ('author', models.ManyToManyField(db_table='publishers_lens_authors', to='publisher.author')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='publisher.image')),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='len',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='publisher.len'),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('source', models.CharField(choices=[('YT', 'YouTube')], max_length=10)),
                ('credit', models.CharField(max_length=15)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_comment='Date and time when the video was created')),
                ('date_updated', models.DateTimeField(auto_now=True, db_comment='Date and time when the video was updated')),
                ('author', models.ManyToManyField(db_table='publishers_videos_authors', to='publisher.author')),
            ],
        ),
        migrations.AddField(
            model_name='len',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='publisher.video'),
        ),
        migrations.AddField(
            model_name='camera',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='publisher.video'),
        ),
        migrations.AddField(
            model_name='review',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='publisher.video'),
        ),
        migrations.DeleteModel(
            name='Cameras',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.DeleteModel(
            name='Lens',
        ),
        migrations.DeleteModel(
            name='Videos',
        ),
    ]
