# Generated by Django 5.0.4 on 2024-07-13 03:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0002_remove_images_author_remove_lens_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='author',
            field=models.ManyToManyField(db_table='publishers_cameras_authors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='image',
            name='author',
            field=models.ManyToManyField(db_table='publishers_images_authors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='len',
            name='author',
            field=models.ManyToManyField(db_table='publishers_lens_authors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.ManyToManyField(db_table='publishers_reviews_authors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='video',
            name='author',
            field=models.ManyToManyField(db_table='publishers_videos_authors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
