# Generated by Django 5.2.3 on 2025-07-03 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0003_delete_author_alter_camera_author_alter_image_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, default='uploads/image/default.png', null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='video',
            name='source_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
