# Generated by Django 5.2.8 on 2025-11-19 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0004_image_image_video_source_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='publisher.camera'),
        ),
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='publisher.image'),
        ),
        migrations.AlterField(
            model_name='review',
            name='len',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='publisher.len'),
        ),
        migrations.AlterField(
            model_name='review',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='publisher.video'),
        ),
    ]
