# Generated by Django 5.2.8 on 2025-11-26 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0005_alter_review_camera_alter_review_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='len',
            old_name='effectivePixels',
            new_name='effective_pixels',
        ),
        migrations.RenameField(
            model_name='len',
            old_name='maxResolution',
            new_name='max_resolution',
        ),
        migrations.RenameField(
            model_name='len',
            old_name='modelName',
            new_name='model_name',
        ),
        migrations.RenameField(
            model_name='len',
            old_name='versionName',
            new_name='version_name',
        ),
    ]
