# Generated by Django 5.2.8 on 2025-11-26 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0006_rename_effectivepixels_len_effective_pixels_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(app_label)s_%(class)s_related', to='publisher.image'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='publisher.video'),
        ),
        migrations.AlterField(
            model_name='len',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='publisher.video'),
        ),
        migrations.AlterField(
            model_name='video',
            name='source_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
