services:
  review_app_redis:
    container_name: review_app_redis
    image: 'redis:7.2.4-alpine'
    ports:
      - "${REDIS_CACHE_PORT}:${REDIS_CACHE_PORT}"
    command: "redis-server --save 20 1 --loglevel warning --user ${REDIS_CACHE_USER} --requirepass ${REDIS_CACHE_PASSWORD}"
  review_app_db:
    container_name: review_app_db
    image: 'mysql:8.0.11'
    volumes:
      - 'mysql_data_review:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: review
      MYSQL_USER: review
      MYSQL_PASSWORD: review
    ports:
      - "33061:3306"
    networks:
      - review_app
  review_app_auth_publisher_py:
    container_name: review_app
    build:
      context: .
      dockerfile: Dockerfile-python
    volumes:
      - "./:/var/www/html/ReviewApp"
    ports:
      - "9090:8000"
    networks:
      - review_app
    depends_on:
      - review_app_db
      - review_app_redis
  review_app_nginx:
    container_name: review_app_server
    image: nginx:latest
    volumes:
      - ./build/nginx.conf:/etc/nginx/nginx.conf
      - ./build/reviewapp.crt:/etc/ssl/certs/reviewapp.crt
      - ./build/reviewapp.key:/etc/ssl/private/reviewapp.key
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - review_app_auth_publisher_py
      - review_app_reader
    networks:
      - review_app
  review_app_reader:
    container_name: review_reader
    build:
      context: ./reader
      dockerfile: Dockerfile-python
    volumes:
      - "./reader/:/var/www/html/ReviewApp/reader"
    ports:
      - "9091:8081"
    networks:
      - review_app
    depends_on:
      - review_app_redis
networks:
  review_app:
    driver: bridge
volumes:
  mysql_data_review: