services:
  review_app_redis:
    container_name: review_app_redis
    image: 'redis:7.2.4-alpine'
    ports:
      - '10001:6379'
    networks:
      - review_app
  review_app_db:
    container_name: review_app_db
    image: 'mysql:8.0.11'
    restart: always
    volumes:
      - 'mysql_data_review:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: review
      MYSQL_USER: review
      MYSQL_PASSWORD: review
    ports:
      - "33061:3306"
    networks:
      - review_app
  review_app_auth_publisher_py:
    container_name: review_app
    build:
      context: .
      dockerfile: Dockerfile-python
    volumes:
      - "./:/var/www/html/ReviewApp"
    ports:
      - "9090:8000"
    networks:
      - review_app
    depends_on:
      - review_app_db
networks:
  review_app:
    driver: bridge
volumes:
  mysql_data_review: