FROM python:3.9

COPY . /var/www/html/ReviewApp/reader

WORKDIR /var/www/html/ReviewApp/reader

RUN pip install --upgrade pip

RUN pip install -r ./requirements.txt

EXPOSE 8081

CMD ["fastapi", "run", "./main.py", "--proxy-headers", "--reload", "--port", "8081"]

